# Generated by Django 5.2.1 on 2025-05-28 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Especialidad')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Especialidad Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_licencia', models.CharField(max_length=50, unique=True, verbose_name='Número de Licencia Médica')),
                ('telefono_consultorio', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono del Consultorio')),
                ('consultorio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número/Nombre del Consultorio')),
                ('activo', models.BooleanField(default=True, verbose_name='Doctor Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('usuario', models.OneToOneField(limit_choices_to={'tipo_usuario': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctores.especialidad', verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'ordering': ['usuario__first_name', 'usuario__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ExcepcionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha y Hora de Inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha y Hora de Fin')),
                ('tipo_excepcion', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('licencia', 'Licencia Médica'), ('reunion', 'Reunión'), ('capacitacion', 'Capacitación'), ('personal', 'Asunto Personal'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo de Excepción')),
                ('motivo', models.TextField(verbose_name='Motivo/Descripción')),
                ('todo_el_dia', models.BooleanField(default=False, help_text='Marcar si la excepción es para todo el día', verbose_name='Todo el Día')),
                ('notificado', models.BooleanField(default=False, help_text='Indica si ya se notificó a los pacientes afectados', verbose_name='Pacientes Notificados')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones_horario', to='doctores.doctor', verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Excepción de Horario',
                'verbose_name_plural': 'Excepciones de Horario',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('duracion_cita', models.IntegerField(default=30, help_text='Duración estándar de cada cita en minutos', verbose_name='Duración de Cita (minutos)')),
                ('activo', models.BooleanField(default=True, verbose_name='Horario Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_atencion', to='doctores.doctor', verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Horario de Atención',
                'verbose_name_plural': 'Horarios de Atención',
                'ordering': ['doctor', 'dia_semana', 'hora_inicio'],
                'unique_together': {('doctor', 'dia_semana')},
            },
        ),
    ]
